#!/bin/bash

# Quick Setup Script for GitHub CLI and Environment Variables
# Run this after the initial deployment

echo "🔧 LL97Plan.com Post-Deployment Setup"
echo "====================================="
echo ""

echo "1️⃣ Setting up GitHub CLI authentication..."
echo "Please follow these steps:"
echo ""
echo "Run: gh auth login"
echo "- Choose: GitHub.com"
echo "- Choose: HTTPS"
echo "- Authenticate in browser"
echo ""

echo "2️⃣ Setting up Vercel environment variables..."
echo ""
echo "Go to: https://vercel.com/dashboard"
echo "1. Select your 'll97plan-deployment' project"
echo "2. Go to Settings > Environment Variables"
echo "3. Add these variables:"
echo ""
echo "SMTP_USER"
echo "  Value: your-email@gmail.com"
echo "  Scope: Production"
echo ""
echo "SMTP_PASS"
echo "  Value: your-gmail-app-password"
echo "  Scope: Production"
echo ""
echo "FROM_EMAIL"
echo "  Value: noreply@ll97plan.com"
echo "  Scope: Production"
echo ""
echo "TO_EMAIL"
echo "  Value: info@ll97plan.com"
echo "  Scope: Production"
echo ""

echo "3️⃣ After setting environment variables:"
echo ""
echo "Go back to your Vercel project and click 'Redeploy'"
echo "This will restart the deployment with the new environment variables."
echo ""

echo "4️⃣ Your live URLs will be:"
echo ""
echo "🌐 Homepage: https://YOUR-PROJECT-NAME.vercel.app/"
echo "🧮 LL97 Calculator: https://YOUR-PROJECT-NAME.vercel.app/pages/ll97-calculator-update.html"
echo "📧 Contact Form: https://YOUR-PROJECT-NAME.vercel.app/pages/contact-page-update.html"
echo "🏗️ Retrofit Calculator: https://YOUR-PROJECT-NAME.vercel.app/pages/retrofit-calculator-update.html"
echo ""

echo "✅ All UAT fixes are now deployed!"
echo ""
echo "🧪 Test these features:"
echo "- LL97 Calculator should show results (not empty page)"
echo "- Contact form should send emails to info@ll97plan.com"
echo "- Retrofit calculator should have improved styling"
echo ""

echo "🎉 LL97Plan.com is now live with all fixes deployed!"
